application:
  config:
    description: Profile Default

server:
  port: ${PORT:8087}

spring:
  application:
    name: bootcoin-service
  data:
    mongodb:
      uri: ${MONGODB_CONNSTRING:mongodb://localhost:27017/bootcoindb}
  #      username: ${MONGO_USERNAME:admin}
  #      password: ${MONGO_PASSWORD:s3cret}
  messages:
    basename: i18n/messages
    fallback-to-system-locale: true
    use-code-as-default-message: true
  jackson:
    default-property-inclusion: NON_NULL
  redis:
    port: 6379
    host: 192.168.1.20
    password: eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
  kafka:
    consumer:
      group-id: bootcoin-group
    producer:
      properties:
        retries: 10
        retry.backoff.ms: 1000
    bootstrap-servers: 192.168.1.20:29093

kafka:
  topic:
    account-request: TOPIC-account-request
    account-response: TOPIC-account-response
    yanki-request: TOPIC-yanki-request
    wallet-request: TOPIC-wallet-request
    wallet-response: TOPIC-wallet-response

cache:
  enabled: true